package Exception;
public class Excep2 {
    public static void main(String args[])
    {
        try
         {         int a;
                    int d=2;
                    a=40/d;
                   System.out.println(a);
        }
        
        catch(ArithmeticException e)
        {
            System.out.println(" Division by Zero Error:"+e);
        }
       
    }
    
}
